Traceback (most recent call last):
  File "/Users/johannes/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/johannes/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/johannes/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/johannes/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/johannes/opt/anaconda3/envs/tf2/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Users/johannes/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/johannes/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/johannes/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from gensim.models import KeyedVectors
# Creating the model
pathMacBookAir='/Users/johannesmaucher/DataSets/fasttextEnglish300.vec'
pathMacBook='/Users/maucher/DataSets/Gensim/FastText/fasttextEnglish300.vec'
pathDeepLearn='../../DataSets/FastText/fasttextEnglish300.vec'
w2vmodel = KeyedVectors.load_word2vec_format(pathMacBook)
EMBEDDING_DIM=w2vmodel.vector_size
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-1-cb742a87c4d1>[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0mpathMacBook[0m[0;34m=[0m[0;34m'/Users/maucher/DataSets/Gensim/FastText/fasttextEnglish300.vec'[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mpathDeepLearn[0m[0;34m=[0m[0;34m'../../DataSets/FastText/fasttextEnglish300.vec'[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m [0mw2vmodel[0m [0;34m=[0m [0mKeyedVectors[0m[0;34m.[0m[0mload_word2vec_format[0m[0;34m([0m[0mpathMacBook[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0mEMBEDDING_DIM[0m[0;34m=[0m[0mw2vmodel[0m[0;34m.[0m[0mvector_size[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/gensim/models/keyedvectors.py[0m in [0;36mload_word2vec_format[0;34m(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype)[0m
[1;32m   1496[0m         return _load_word2vec_format(
[1;32m   1497[0m             [0mcls[0m[0;34m,[0m [0mfname[0m[0;34m,[0m [0mfvocab[0m[0;34m=[0m[0mfvocab[0m[0;34m,[0m [0mbinary[0m[0;34m=[0m[0mbinary[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m,[0m [0municode_errors[0m[0;34m=[0m[0municode_errors[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1498[0;31m             limit=limit, datatype=datatype)
[0m[1;32m   1499[0m [0;34m[0m[0m
[1;32m   1500[0m     [0;32mdef[0m [0mget_keras_embedding[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mtrain_embeddings[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/gensim/models/utils_any2vec.py[0m in [0;36m_load_word2vec_format[0;34m(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype)[0m
[1;32m    340[0m [0;34m[0m[0m
[1;32m    341[0m     [0mlogger[0m[0;34m.[0m[0minfo[0m[0;34m([0m[0;34m"loading projection weights from %s"[0m[0;34m,[0m [0mfname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 342[0;31m     [0;32mwith[0m [0mutils[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0;34m'rb'[0m[0;34m)[0m [0;32mas[0m [0mfin[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    343[0m         [0mheader[0m [0;34m=[0m [0mutils[0m[0;34m.[0m[0mto_unicode[0m[0;34m([0m[0mfin[0m[0;34m.[0m[0mreadline[0m[0;34m([0m[0;34m)[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    344[0m         [0mvocab_size[0m[0;34m,[0m [0mvector_size[0m [0;34m=[0m [0;34m([0m[0mint[0m[0;34m([0m[0mx[0m[0;34m)[0m [0;32mfor[0m [0mx[0m [0;32min[0m [0mheader[0m[0;34m.[0m[0msplit[0m[0;34m([0m[0;34m)[0m[0;34m)[0m  [0;31m# throws for invalid file format[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/smart_open/smart_open_lib.py[0m in [0;36mopen[0;34m(uri, mode, buffering, encoding, errors, newline, closefd, opener, ignore_ext, transport_params)[0m
[1;32m    306[0m         [0mbuffering[0m[0;34m=[0m[0mbuffering[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    307[0m         [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 308[0;31m         [0merrors[0m[0;34m=[0m[0merrors[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    309[0m     )
[1;32m    310[0m     [0;32mif[0m [0mfobj[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/tf2/lib/python3.7/site-packages/smart_open/smart_open_lib.py[0m in [0;36m_shortcut_open[0;34m(uri, mode, ignore_ext, buffering, encoding, errors)[0m
[1;32m    515[0m     [0;31m#[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    516[0m     [0;32mif[0m [0msix[0m[0;34m.[0m[0mPY3[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 517[0;31m         [0;32mreturn[0m [0m_builtin_open[0m[0;34m([0m[0mparsed_uri[0m[0;34m.[0m[0muri_path[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0mbuffering[0m[0;34m=[0m[0mbuffering[0m[0;34m,[0m [0;34m**[0m[0mopen_kwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    518[0m     [0;32melif[0m [0;32mnot[0m [0mopen_kwargs[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    519[0m         [0;32mreturn[0m [0m_builtin_open[0m[0;34m([0m[0mparsed_uri[0m[0;34m.[0m[0muri_path[0m[0;34m,[0m [0mmode[0m[0;34m,[0m [0mbuffering[0m[0;34m=[0m[0mbuffering[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/maucher/DataSets/Gensim/FastText/fasttextEnglish300.vec'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/maucher/DataSets/Gensim/FastText/fasttextEnglish300.vec'

