Traceback (most recent call last):
  File "/Users/johannes/opt/anaconda3/envs/dsmmlbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/johannes/opt/anaconda3/envs/dsmmlbook/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/johannes/opt/anaconda3/envs/dsmmlbook/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/johannes/opt/anaconda3/envs/dsmmlbook/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/johannes/opt/anaconda3/envs/dsmmlbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/johannes/opt/anaconda3/envs/dsmmlbook/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/johannes/opt/anaconda3/envs/dsmmlbook/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/johannes/opt/anaconda3/envs/dsmmlbook/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
if FASTTEXT:
    from gensim.models import KeyedVectors
    # Creating the model
    iMacPath="/Users/johannes/DataSets/nlp/wiki-news-300d-1M.vec"
    pathMacBook='/Users/maucher/DataSets/Gensim/FastText/fasttextEnglish300.vec'
    pathDeepLearn='../../DataSets/FastText/fasttextEnglish300.vec'
    w2vmodel = KeyedVectors.load_word2vec_format(iMacPath)
    EMBEDDING_DIM=w2vmodel.vector_size
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/var/folders/68/9tltm6l520v0stj3qjlc5v9w0000gn/T/ipykernel_24034/2464186857.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mif[0m [0mFASTTEXT[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m     [0;32mfrom[0m [0mgensim[0m[0;34m.[0m[0mmodels[0m [0;32mimport[0m [0mKeyedVectors[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m     [0;31m# Creating the model[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0miMacPath[0m[0;34m=[0m[0;34m"/Users/johannes/DataSets/nlp/wiki-news-300d-1M.vec"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mpathMacBook[0m[0;34m=[0m[0;34m'/Users/maucher/DataSets/Gensim/FastText/fasttextEnglish300.vec'[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'gensim'
ModuleNotFoundError: No module named 'gensim'

